name = "Hyperspace"
min_version = "0.54.0"

[author]
  name = "Felix Linker"
  homepage = "http://felixlinker.de"

# If porting an existing theme
[original]
  name = "hyperspace"
  homepage = "https://html5up.net/"
