baseURL = "http://felixlinker.de/"
languageCode = "en-us"
title = "Felix Linker"
theme = "hello-friend"
defaultContentLanguage = "en"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

[author]
    name = "Felix Linker"

[params]
    description = "Some information about Felix Linker"
    homeSubtitle = "I will soon start a PhD and have a M.Sc. Computer Science with a B.A. Philosophy"

    contentTypeName = "works"

[params.logo]
    logoText     = "$ cd /home/"
    logoHomeLink = "/"

# Social icons
[[params.social]]
    name = "github"
    url  = "https://github.com/felixlinker"

[[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/felixlinker/"

[[params.social]]
    name = "twitter"
    url  = "https://twitter.com/felixlinker"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "works"
    name       = "Projects"
    url        = "works/"
