baseURL = "http://felixlinker.de/"
languageCode = "en-us"
title = "Felix E. Linker"
theme = "researcher"
defaultContentLanguage = "en"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

[author]
  name = "Felix E. Linker"

[params]
  author = "Felix E. Linker"
  description = "Felix Linker is a PhD student and Scientific Assistant in the Information Security group at ETH Zurich"
  [[params.socialIcons]]
    icon = "fas fa-university"
    title = "ETHZ"
    url  = "https://infsec.ethz.ch/people/detail.Mjc2MDIx.TGlzdC8zMDg4LC0xMDQxNjk2MDky.html"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url  = "https://github.com/felixlinker"
  [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "LinkedIn"
    url  = "https://www.linkedin.com/in/felixlinker/"
  [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url  = "https://twitter.com/felixlinker"
  [[params.socialIcons]]
    icon = "fas fa-address-card"
    title = "Contact"
    url  = "/doc/Linker.vcard.vcf"

[menu]
  [[menu.main]]
    identifier = "works"
    name       = "Projects"
    url        = "/works"
  [[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact"
