baseURL = "http://felixlinker.de/"
languageCode = "en-us"
title = "Felix Linker"
theme = "hyperspace"
author = "Felix Linker"
defaultContentLanguage = "en"

[[menu.main]]
    name = "Experiences"
    weight = 1
    identifier = "cv"

[[menu.main]]
    name = "Works & Projects"
    weight = 2
    identifier = "works"

[params]
    author = "Felix Linker"
    description = "Some information about Felix Linker"
    selfintro = "Student of M.Sc. Computer Science and B.A Philosophy"
    github = "https://github.com/felixlinker"
    facebook = "https://www.facebook.com/felix.linker"
    twitter = "https://twitter.com/felixlinker"
    avatar = "img/avatar.jpg"
