baseURL = "http://felixlinker.de/"
languageCode = "en-us"
title = "Felix Linker"
theme = "researcher"
defaultContentLanguage = "en"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

[author]
  name = "Felix Linker"

[params]
  author = "Felix Linker"
  description = "Felix Linker is a PhD student and Scientific Assistant in the Information Security group at ETH Zurich"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-Mail"
    url  = "mailto:linkerfelix@gmail.com"
  [[params.socialIcons]]
    icon = "fas fa-university"
    title = "ETHZ"
    url  = "https://infsec.ethz.ch/people/detail.Mjc2MDIx.TGlzdC8zMDg4LC0xMDQxNjk2MDky.html"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url  = "https://github.com/felixlinker"
  [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "LinkedIn"
    url  = "https://www.linkedin.com/in/felixlinker/"
  [[params.socialIcons]]
    icon = "fab fa-x-twitter"
    title = "X"
    url  = "https://twitter.com/felixlinker"
  [[params.socialIcons]]
    icon = "fab fa-mastodon"
    title = "Mastodon"
    url = "https://infosec.exchange/@felixlinker"

[menu]
  [[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact"
